ALTER TABLE tbl_customer
  ADD COLUMN IF NOT EXISTS profile_photo VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ssn VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS signature VARCHAR(255) DEFAULT NULL;